### ISSUE TITLE
pac 1.9.8 fail to unpack my canvas app with 'non recoverable error'

### ISSUE THREAD

**Issue by megel** [microsoft/powerplatform-vscode#120]
Since yesterday, pac is not longer able to unpack my canvas app. 

The current (latest) **pac version** is **1.9.8**

**The command:**
```
pac canvas unpack --msapp ./app.msapp --sources ./src
```

**Error Output**
```
UnPack from R:\test\app.msapp-->R:\test\src
Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id:95125a45-24c1-4dca-90db-b65e216c943e
```

An older version (1.9.4 from yesterday) works:
```
pac install 1.9.4
pac use 1.9.4
pac canvas unpack --msapp ./app.msapp --sources ./src
```

The output and result is as expected:
```
UnPack from R:\test\app.msapp-->R:\test\src                                                                                                                                                                      source format version: 0.24
```

**Comment by megel** [comment]
Related to: https://github.com/microsoft/PowerApps-Language-Tooling/issues/310

**Comment by tehcrashxor** [comment]
The PAC bug has been fixed with yesterday's release of [PAC v1.9.9](https://www.nuget.org/packages/Microsoft.PowerApps.CLI/1.9.9).

The VS Code Extension took that fix with #128 , which is now released and published to the VS Marketplace as v0.2.23

**Comment by hankanman** [comment]
NOT Resolved. Still receiving this error with studio release: 3.21112.22 and 3.21111.35

Found that it will unpack with these studio versions with a blank app (just created new, added a label and published.

Will NOT unpack the second a component is added

Added component library to solution as well, component library also fails to unpack as well as the apps dependant on it.

Error as above received:
Component Library:
`Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id:50b318f9-092d-456d-8fa5-481e63542ca9`

Test app with only a label and one component from component library:
`Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id:3e64338e-1048-4fad-a3ad-c6bbb8a380df`

For Canvas app using the components:
`Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id:b19fd1dc-707d-45a8-bcd5-4d375cc24238`

Telemetry enabled, I assume the exception ID's for each are useful

Yes yes I know components are in "Preview" but you can't have an almost critical feature in preview for how ever many years at this point and not GA it at some point....
